version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    working_directory: ~/environment
    steps:
      - checkout
      - run: yarn install && yarn build
      - persist_to_workspace:
          root: "."
          paths:
            - dist/
            - .firebaserc
            - firebase.json
            - functions/
  deploy:
    docker:
      - image: circleci/node:9
    working_directory: ~/environment
    steps:
      - attach_workspace:
          at: "."
      - run: yarn global add firebase-tools
      - run: ls -la
      - run: firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # filters:
          #   branches:
          #     only: sequential-branch-filter